language: node_js
node_js:
- 0.10.30
after_success:
- echo $TOTO
- git remote -v
- git config --global user.email "deepak.kowshika@gmail.com"
- git config --global user.name "deepak.kowshika@gmail.com"
- git checkout master
- npm version patch
- git commit -am "[skip ci] bump version"
- git log --oneline
- git remote set-url origin git@github.com:ksdeepak93/travis.git
- git push origin master

script:
- node hello.js
# - npm run coverage
# - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
# - cat ./coverage/lcov.info | codeclimate
